name: CMake on Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  c_ProjectName: "PropertyEditor"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install Qt5 Compatible Libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libqt5core5a \          # Qt5 核心库
          libqt5gui5 \            # Qt5 GUI 库
          libqt5widgets5 \         # Qt5 Widgets 库
          libqt5charts5 \          # Qt5 Charts 库
          libqt5svg5 \             # Qt5 SVG 库
          libqt5charts5-dev \      # Qt5 Charts 开发文件
          libqt5svg5-dev \         # Qt5 SVG 开发文件
          qtbase5-dev \            # Qt5 基础开发文件
          libgl1-mesa-dev \        # OpenGL 支持
          libxcb-xinerama0-dev     # X11 集成
        
        # 验证安装的 Qt 库版本
        dpkg -l | grep 'libqt5'
    
    - name: Check Submodules
      run: |
        echo "检查子模块状态"
        ls -la ThirdParty/CMakeProjectFramework
    
    - name: Configure CMake
      working-directory: Build/${{env.c_ProjectName}}/Linux
      run: |
        echo "当前工作目录: $(pwd)"
        ./Generate.sh
    
    - name: Build
      working-directory: Build/${{env.c_ProjectName}}/Linux
      run: |
        ./Build.sh
    
    # - name: Run Application
    #   working-directory: Build/${{env.c_ProjectName}}/Linux/DefaultBuild/Release/bin
    #   run: |
    #     ./${{env.c_ProjectName}}