# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  c_ProjectName: "HelloWorld"

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:  # 必须用 with 包裹参数
        submodules: recursive  # 关键：递归克隆子模块, 操作包含 git submodule update --init --remote
        token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 自动生成的 Token, 用于更新 submodule

    - name: Install Dependencies  # Linux 系统需要安装构建工具
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Check Submodules
      run: |
        echo "检查子模块状态"
        ls -la ThirdParty/CMakeProjectFramework

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      #run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      working-directory: Build/${{env.c_ProjectName}}/Linux
      run: |
        echo "当前工作目录: $(pwd)"
        ./Generate.sh

    - name: Build
      # Build your program with the given configuration
      #run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      working-directory: Build/${{env.c_ProjectName}}/Linux
      run: |
        ./Build.sh

    - name: Run
      working-directory: Build/${{env.c_ProjectName}}/Linux/DefaultBuild/Release/bin
      run: |
        ./${{env.c_ProjectName}}


    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  # Execute tests defined by the CMake configuration.
    #  # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C ${{env.BUILD_TYPE}}

