name: CMake on Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  c_ProjectName: "PropertyEditor"

jobs:
  build:
    runs-on: ubuntu-24.04  # 明确使用 Ubuntu 24.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install Qt5 Dependencies
      run: |
        sudo apt-get update
        
        # Ubuntu 24.04 中 Qt5 包的新名称
        sudo apt-get install -y \
          build-essential \
          cmake \
          qtbase5-dev \           # Qt5 基础开发文件
          libqt5svg5-dev \        # Qt5 SVG 开发文件
          libqt5charts-dev \      # Qt5 Charts 开发文件
          libgl1-mesa-dev \       # OpenGL 支持
          libxkbcommon-x11-0 \    # X11 集成
          libxcb-xinerama0-dev    # X11 窗口管理
        
        # 验证安装的 Qt 库版本
        dpkg -l | grep 'libqt5' | grep 'dev'
    
    - name: Check Submodules
      run: |
        echo "检查子模块状态"
        ls -la ThirdParty/CMakeProjectFramework
    
    - name: Configure CMake
      working-directory: Build/${{env.c_ProjectName}}/Linux
      run: |
        echo "当前工作目录: $(pwd)"
        ./Generate.sh
    
    - name: Build
      working-directory: Build/${{env.c_ProjectName}}/Linux
      run: |
        ./Build.sh
    
    # - name: Run Application
    #   working-directory: Build/${{env.c_ProjectName}}/Linux/DefaultBuild/Release/bin
    #   run: |
    #     ./${{env.c_ProjectName}}