name: CMake on Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  c_ProjectName: "PropertyEditor"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install PyQt5 for Qt5 Compatibility
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3 \
          python3-pip \
          python3-pyqt5 \          # PyQt5 核心
          python3-pyqt5.qtcharts \ # PyQt5 Charts 模块
          python3-pyqt5.qtsvg     # PyQt5 SVG 模块
        
        # 验证安装
        python3 -c "from PyQt5 import QtCore; print('PyQt5 version:', QtCore.PYQT_VERSION_STR)"
        python3 -c "from PyQt5 import QtCharts; print('QtCharts module available')"
        python3 -c "from PyQt5 import QtSvg; print('QtSvg module available')"
        
        # 设置环境变量（如果需要）
        echo "PYTHONPATH=/usr/lib/python3/dist-packages" >> $GITHUB_ENV
    
    - name: Check Submodules
      run: |
        echo "检查子模块状态"
        ls -la ThirdParty/CMakeProjectFramework
    
    - name: Configure CMake
      working-directory: Build/${{env.c_ProjectName}}/Linux
      run: |
        echo "当前工作目录: $(pwd)"
        ./Generate.sh
    
    - name: Build
      working-directory: Build/${{env.c_ProjectName}}/Linux
      run: |
        ./Build.sh
    
    # - name: Run Application
    #   working-directory: Build/${{env.c_ProjectName}}/Linux/DefaultBuild/Release/bin
    #   run: |
    #     ./${{env.c_ProjectName}}